PUSH = oopj.commands.PushCommand
POP = oopj.commands.PopCommand
PRINT = oopj.commands.PrintCommand
DEFINE = oopj.commands.DefineCommand
+ = oopj.commands.AddCommand
- = oopj.commands.SubtractionCommand
* = oopj.commands.MultiplyCommand
/ = oopj.commands.DivisionCommand
SQRT = oopj.commands.SqrtCommand
